---
title: 'Bush-2022'
---

# Lessons Learned: A Neuroimaging Research Center's Transition to Open and Reproducible Science

-   File: data/review/fulltext/oa-id-W4283836446.pdf
-   DOI: https://doi.org/10.31219/osf.io/fe74t
-   OpenAlex ID: https://openalex.org/W4283836446

## Characteristics of the paper

-   Type of paper (e.g., tips, example): example
-   Themes (e.g., tools, organization): tools, workflow
-   Other keywords (e.g., newcomers):

## Tools

### Specific tools mentioned - their function - where in the researh process used

-   Github - open-source code, version control, collaboration -
    analysing
-   Python - open-source programming - analysing
-   R - open-source programming - analysing
-   arXiv/bioRxiv/psyRxiv - preprint sharing - disseminating
-   OpenNeuro - data sharing - disseminating
-   Open Science Framework - preregistration - planning
-   clinicaltrials.gov - preregistration - planning
-   FAIR (findability", "accessibility", "interoperability", and
    "reusability") -principles to organize data, not a tool per se, but
    I think they need to be emphasized - data collection, organization
    and sharing -
-   Brain imaging data structure (BIDS) - a common and standardized
    framework all scientists can work on - data collection and sharing
-   Containarized pipelines - code that allows easy reproduction - data
    analysis
-   ReproBIDS - dictionary with standardized terms for BIDS neuro data -
    planning, data collection, data deposition

## Organizational structure for open collaboration

### Workflow

-   The steps below were identified after: 1) assessing the crisis of
    reproducibility, 2) literature search (systematic review) #worth
    noting since it pops up in so many papers as a previous step to
    implementation.

-   hypothesis - experiment - data collection - data analysis -
    reporting

### Centre workflow of practices to become more open (the ones above are more on the individual level)

-   publish code, publishing pre-prints, standardizing data to BIDS,
    transition to containarized pipelines, publish data in repositories,
    establish data dictionaries, pre-registration,

## Educational perspectives

### Educational needs

-   people in the organization need to learn additional programming,
    version control, and data management skills and work with unfamiliar
    naming conventions and directory structures mandated by the used
    standards

## Barriers

### Barriers for open science

-   costs of effort to be borne by individuals already engaged in
    challenging, time-consuming work
-   during transition, the research productivity will suffer
