---
title: 'Reviews by Daniel'
---

# Open and reproducible neuroimaging: From study inception to publication

-   File: data/review/fulltext/oa-id-W4295290221.pdf
-   DOI: https://doi.org/10.1016/j.neuroimage.2022.119623
-   OpenAlex ID: https://openalex.org/W4295290221

## General themes

-   tools
-   workflow

## Type of paper

-   guide

## Other notes

-   This paper is not much about open collaboration but more about which
    tools to use for open and reproducible research from start to finish
    of a project.
-   Study inception, planning, and ethics: OSF pre-registration,
    clinicaltrials.gov, aspredicted
-   Data processing and analysis: git, github, gitlab, etc
-   Scientific research can now become more transparent, inclusive and
    collaborative throughout the research cycle
-   Publishing Code of Conduct for collaborative projects is one
    practice that helps ensure a more welcoming and inclusive space for
    everyone regardless of background or identity

# Ten simple rules for helping newcomers become contributors to open projects

-   File: data/review/fulltext/oa-id-W2972809368.pdf
-   DOI: https://doi.org/10.1371/journal.pcbi.1007296
-   OpenAlex ID: https://openalex.org/W2972809368

## General themes

-   community building
-   social rules
-   organization around the collaboration
-   new comers

## Type of paper

-   guide

## Other notes

-   Focus on building community: 1: be welcoming, 3. make governance
    explicit, 6. Develop forms of legitimate peripheral
    participation, 7. Make it easy for newcomers to get started.

# Collaborative open science as a way to reproducibility and new insights in primate cognition research

-   File: data/review/fulltext/oa-id-W4251805646.pdf
-   DOI: https://doi.org/10.31234/osf.io/8w7zd
-   OpenAlex ID: https://openalex.org/W4251805646

## General themes

-   collaboration structure
-   tools
-   organization

## Type of paper

-   example

## Other notes

-   Focus on large-scale collaboration in psychology, because of a main
    challenge of small samples sizes.
-   Project started in connection with a conference. First paper was a
    pilot. Main aim of the project is to provide infrastructure for
    large-scale collaboration. Used mailing list to share information,
    then slack for discussions. Use Google docs for writing and
    documentation and github for code and data. Data analysis plans
    pre-registered at OSF.
-   Have a website - good for newcomers and sharing info. Topic for
    research selected through voting. After organizing the data, they
    had a modelling challenge. Also discuss challenges. Main one was how
    to make decisions.
-   Leadership team preferable. Also have author guidelines.

# Promoting FAIR Data Through Community-driven Agile Design: the Open Data Commons for Spinal Cord Injury (odc-sci.org)

-   File: data/review/fulltext/oa-id-W3188722327.pdf
-   DOI: https://doi.org/10.1007/s12021-021-09533-8
-   OpenAlex ID: https://openalex.org/W3188722327

## General themes

-   data sharing
-   organization

## Type of paper

-   example

## Other notes

-   this paper is mostly about a database for sharing spinal injury
    data. There are some points for how to improve sharing but not much
    about open collaboration
-   open data commons for spinal injury
-   studies based on game theory suggest that data sharing might be
    beneficial if a collaborative approach is taken and data sharing is
    embraced as a community rather than by individuals
-   key events for the collaboration to be possible: - introduction of
    FAIR principles, update from funders, funding given to specific
    projects
-   Open Data Commons for SCI (ODC-SCI, odc-sci.org), a platform to
    share tabular data of research in the field of spinal cord injury
-   Aim of the paper: to illustrate how members of research communities
    can work together toward the development of dedicated data sharing
    initiatives under the umbrella of FAIR
-   clearly highlighted the value of the massive demonstration/work for
    beta testing the site to reveal unforeseen problems
-   Moreover, participants pointed out the need for improving
    self-explanatory tutorials and help materials that would facilitate
    the learning experience for those who could not attend the workshop
-   "Registered users can request to become ODC-SCI Community members
    with further approval by the Leadership team." The most permissive
    account type is becoming an ODC-SCI Community member associated to
    an ODC-SCI lab, known as a Lab member

# UKRN Open Research Training Resources and Priorities Working Paper

-   File: data/review/fulltext/oa-id-W4372403418.pdf
-   DOI: https://doi.org/10.31219/osf.io/s2f6k
-   OpenAlex ID: https://openalex.org/W4372403418

## General themes

-   organization
-   training

## Type of paper

-   survey
-   recommendations

## Other notes

-   aim of the survey is to inform training priorities for open science
-   research cycle: planning, conducting, analysing, disseminating
-   Planning: team science guides, research co-production
-   Conducting: open research testing platforms
-   Most resources focus on the planning and analysing stage
-   Many resources were only for internal use
-   Very few resources for open collaboration, none were open and they
    were valued poorly compared to other practices

# Eleven Strategies for Making Reproducible Research and Open Science Training the Norm at Research Institutions

-   File: data/review/fulltext/oa-id-W4378611187.pdf
-   DOI: https://doi.org/10.31219/osf.io/kcvra
-   OpenAlex ID: https://openalex.org/W4378611187

## General themes

-   training
-   recommendations
-   organization

## Type of paper

-   survey

## Other notes

-   Strategy 5 - Perform replication or meta-research studies as course
    projects: As the class collaborates on one project, participants
    also build skills for collaborative team science and gain experience
    leading small teams.
-   Tips for Strategy 5 - Perform replication or meta-research studies
    as course projects: Carefully define the scope of the project,
    Ensure that you have adequate support
-   build communities: Foster accessible discussions (Consider running
    "beginner" and "advanced" community meetings), Build communities:
    Organize regular meetings

# Collaboration and Open Science Initiatives in Primate Research

-   File: data/review/fulltext/oa-id-W3183365357.pdf
-   DOI: https://doi.org/10.31219/osf.io/7c93a
-   OpenAlex ID: https://openalex.org/W3183365357

## General themes

-   large-scale collaboration
-   organization
-   tools

## Type of paper

-   example

## Other notes

-   for them, making the large-scale collaboration was about overcoming
    challenges related to their research
-   Large-scale collaborations can help to set standards in the field by
    following good scientific practice of replications, data reporting,
    and pre-registration
-   Low entry barriers and the various ways in which a scientist can be
    involved in a large-scale collaboration (design, data collection,
    analysis, manuscript writing) offer a multitude of possibilities for
    researchers in different stages of their careers
-   These types of projects also present valuable opportunities to make
    new contacts, initiate new collaborations, and connect with a bigger
    community on a regular basis
-   Large-scale collaborations represent a wholesale shift in scientific
    practice, from how research questions are chosen and approached, to
    how research is logistically coordinated and how credit for research
    efforts is allocated
-   large-scale collaborative projects may reduce the diversity of
    topics by covering them at a scale that would be unfeasible by
    independent research groups
-   Agreeing on project selection, study design, stimuli, analysis plan,
    and findings' interpretation is not easy in big groups. (...)
    research questions are selected democratically - proposals for
    projects are submitted and members vote to select which projects
    will be carried out.
-   Large-scale projects also have to develop authorship guidelines,
    which specify the minimal conditions that one person has to fulfill
    to qualify for authorship
-   none of the large-scale consortia in psychology have a steady source
    of financing
-   setup the project to be long-lasting and build an infrastructure
    that they piloted
-   task forces within the project prepared different materials they
    then uploaded to github and pre-register

# Open and reproducible practices in developmental psychology research: The workflow of the WomCogDev lab as an example

-   File: data/review/fulltext/oa-id-W4229452124.pdf
-   DOI: https://doi.org/10.31234/osf.io/73bwu
-   OpenAlex ID: https://openalex.org/W4229452124

## General themes

-   tools
-   workflow

## Type of paper

-   guide

## Other notes

-   Nice figure with workflow
-   Resources: lab meetings, slack, trello, OSF repository
-   They setup a clear structure for how to conduct the research - how a
    project is supposed to work
-   Open Science is never static, as each of us continues to incorporate
    more and more practices into our repertoires over time

# Accelerating addiction research via Open Science and Team Science

-   File: data/review/fulltext/oa-id-W4383376256.pdf
-   DOI: https://doi.org/10.31234/osf.io/pbkrx
-   OpenAlex ID: https://openalex.org/W4383376256

## General themes

-   organisation

## Type of paper

-   guide
-   example

## Other notes

-   mentions registered reports that are peer reviewer twice
-   recommend sharing on OSF
-   synthpop package in R creates a synthetic dataset with same
    statistical properties
-   large-scale collaboration is recommended to improve generalizability
    and power.
-   they provide an example of an individual-participant meta-analysis
    they conducted
-   As part of this process, we made several decisions as a group (via
    an anonymous poll), such as which smallest effect size of interest
    to preregister and to which journal to submit the paper
-   Barriers: within our current scientific culture, there are few
    incentives to work in large teams, all large-scale collaborations
    need leadership

# Ten strategies to foster open science in psychology and beyond

-   File: data/review/fulltext/oa-id-W4281886503.pdf
-   DOI: https://doi.org/10.31234/osf.io/c38a2
-   OpenAlex ID: https://openalex.org/W4281886503

## General themes

-   tools
-   organization
-   large-scale collaboration

## Type of paper

-   guide

## Other notes

-   Strategy 6: Collaborate with Others Using Open Tools
-   can get started by writing in markdown/quarto, using github
-   Strategy 7: Develop Networks of Open Collaboration
-   Big Team Science has advantages for research, as it allows
    investigators to access more resources, work with greater sample
    sizes, take advantage of the expertise of a larger team of
    researchers in areas such as data analysis, and distribute work more
    efficiently
-   Participating in these large-scale projects is not easy and calls on
    researchers to develop specific standards and guidelines that ensure
    effective communication among collaborators and enable projects to
    develop coherently and cohesively
-   there is still a long way to go before open science becomes the
    by-design and by-default model for scientific research

# Open and collaborative tools for disaster management and risk reduction

-   File: data/review/fulltext/oa-id-W4303191041.pdf
-   DOI: https://doi.org/10.36335/vnjhm.2022(12).33-38
-   OpenAlex ID: https://openalex.org/W4303191041

## General themes

-   could not access

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# UKRN ORCC Primer on Working in Open Research

-   File: data/review/fulltext/oa-id-W4386723394.pdf
-   DOI: https://doi.org/10.31219/osf.io/346hr
-   OpenAlex ID: https://openalex.org/W4386723394

## General themes

-   not relevant. Is about working in open research not performing it

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Lessons Learned: A Neuroimaging Research Center's Transition to Open and Reproducible Science

-   File: data/review/fulltext/oa-id-W4283836446.pdf
-   DOI: https://doi.org/10.31219/osf.io/fe74t
-   OpenAlex ID: https://openalex.org/W4283836446

## General themes

-   workflow
-   tools

## Type of paper

-   guide

## Other notes

-   also nice figure of workflow including open science practices in the
    workflow
-   use OSF for registering protocols
-   focus on open software like R and Python, git and github
-   this is a practical guide to make a transition, very little
    mentioned specifically about collaboration or team work
