---
title: 'Reviews by Mario'
---

# Open and reproducible neuroimaging: From study inception to publication

-   File: data/review/fulltext/oa-id-W4295290221.pdf
-   DOI: https://doi.org/10.1016/j.neuroimage.2022.119623
-   OpenAlex ID: https://openalex.org/W4295290221

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Ten simple rules for helping newcomers become contributors to open projects

-   File: data/review/fulltext/oa-id-W2972809368.pdf
-   DOI: https://doi.org/10.1371/journal.pcbi.1007296
-   OpenAlex ID: https://openalex.org/W2972809368

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Collaborative open science as a way to reproducibility and new insights in primate cognition research

-   File: data/review/fulltext/oa-id-W4251805646.pdf
-   DOI: https://doi.org/10.31234/osf.io/8w7zd
-   OpenAlex ID: https://openalex.org/W4251805646

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Promoting FAIR Data Through Community-driven Agile Design: the Open Data Commons for Spinal Cord Injury (odc-sci.org)

-   File: data/review/fulltext/oa-id-W3188722327.pdf
-   DOI: https://doi.org/10.1007/s12021-021-09533-8
-   OpenAlex ID: https://openalex.org/W3188722327

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# UKRN Open Research Training Resources and Priorities Working Paper

-   File: data/review/fulltext/oa-id-W4372403418.pdf
-   DOI: https://doi.org/10.31219/osf.io/s2f6k
-   OpenAlex ID: https://openalex.org/W4372403418

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Eleven Strategies for Making Reproducible Research and Open Science Training the Norm at Research Institutions

-   File: data/review/fulltext/oa-id-W4378611187.pdf
-   DOI: https://doi.org/10.31219/osf.io/kcvra
-   OpenAlex ID: https://openalex.org/W4378611187

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Collaboration and Open Science Initiatives in Primate Research

-   File: data/review/fulltext/oa-id-W3183365357.pdf
-   DOI: https://doi.org/10.31219/osf.io/7c93a
-   OpenAlex ID: https://openalex.org/W3183365357

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Open and reproducible practices in developmental psychology research: The workflow of the WomCogDev lab as an example

-   File: data/review/fulltext/oa-id-W4229452124.pdf
-   DOI: https://doi.org/10.31234/osf.io/73bwu
-   OpenAlex ID: https://openalex.org/W4229452124

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Accelerating addiction research via Open Science and Team Science

-   File: data/review/fulltext/oa-id-W4383376256.pdf
-   DOI: https://doi.org/10.31234/osf.io/pbkrx
-   OpenAlex ID: https://openalex.org/W4383376256

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Ten strategies to foster open science in psychology and beyond

-   File: data/review/fulltext/oa-id-W4281886503.pdf
-   DOI: https://doi.org/10.31234/osf.io/c38a2
-   OpenAlex ID: https://openalex.org/W4281886503

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Open and collaborative tools for disaster management and risk reduction

-   File: data/review/fulltext/oa-id-W4303191041.pdf
-   DOI: https://doi.org/10.36335/vnjhm.2022(12).33-38
-   OpenAlex ID: https://openalex.org/W4303191041

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# UKRN ORCC Primer on Working in Open Research

-   File: data/review/fulltext/oa-id-W4386723394.pdf
-   DOI: https://doi.org/10.31219/osf.io/346hr
-   OpenAlex ID: https://openalex.org/W4386723394

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::

# Lessons Learned: A Neuroimaging Research Center’s Transition to Open and Reproducible Science

-   File: data/review/fulltext/oa-id-W4283836446.pdf
-   DOI: https://doi.org/10.31219/osf.io/fe74t
-   OpenAlex ID: https://openalex.org/W4283836446

## General themes

::: content-hidden
Look for what the paper is generally about and some basic overall themes
and topics in the paper.
:::

## Type of paper

::: content-hidden
Is it a guide, community-building, an example of a workflow, etc.
:::

## Other notes

::: content-hidden
What we found was interesting or what we'd like to share, discuss, or
present in the main scoping review paper.
:::
