project:
  type: website

execute:
  freeze: auto

website:
  title: "Open Collaboration Scoping Review"
  site-url: "https://science-collective.github.io/scoping-review"
  repo-url: "https://github.com/science-collective/scoping-review"
  navbar:
    pinned: true
    left:
    - text: Protocol
      href: doc/protocol.qmd
    - text: Article
      href: doc/paper.qmd
    - doc/appendices.qmd
  sidebar:
    - id: appendices
      pinned: true
      style: floating
      contents:
        - doc/appendices.qmd
        - CONTRIBUTING.md
        - CODE_OF_CONDUCT.md
        - GOVERNANCE.md
        - ROADMAP.md
        - auto: doc/instructions/
        - auto: doc/reviews/
        - auto: doc/charting/
        - auto: doc/reflections/

format: html

bibliography: doc/references.bib
csl: doc/vancouver.csl
