---
title: 'Introduction to scoping review on open collaboration and experiences with working reproducibly and using GitHub'
date: "2024-06-03"
date-format: long
author:
  - Daniel B. Ibsen
location: "Steno Diabetes Center Aarhus"
format: 
  revealjs:
    fig-align: center
    from: markdown+emoji
    theme:
      - dark
    progress: true
    embed-resources: true
editor: 
  markdown: 
    wrap: 72
    canonical: true
---

# The Polymath problem - revisited

Recall the example from the research retreat.

They used open collaboration to solve a very complex problem.

## Open collaboration {.center}

Today, scientific research almost always requires working with other
people. And with the growing complexity and specialization in scientific
practices and methods, together with globalisation of health and
environmental issues, there is a great need for a paradigm shift in
research collaboration to be able to tackle these challenges.

Open collaboration may offer this solution. Open collaboration is
defined as:

> "*an online environment that (a) supports the collective production of
> an artifact (b) through a technologically mediated collaboration
> platform (c) that presents a low barrier to entry and exit and (d)
> supports the emergence of persistent but malleable social
> structures.*" This scoping review will focus on current practices of
> open collaboration and open science in relation to collaboration in
> the field of biomedical and health research (Forte and Lampe (2013)).

## Aim of scoping review {.center}

Our overarching aim of this scoping review is to identify current
practices of open collaboration in biomedical and health research.

The specific aims of this scoping review are to:

-   Provide an overview of current practices of or opinions about
    research collaboration that follow basic open principles (e.g.,
    transparency, accessibility)

-   Summarize existing online tools and resources available to improve
    open collaboration in research

-   building an open source R-based pipeline for conducting scoping
    reviews.

The entire source code, as well as text and collaboration workflows, are
found on our GitHub repository
[`science-collective/scoping-review`](https://github.com/science-collective/scoping-review).

## Process {.center}

1.  Select topic

2.  Workflow

3.  Protocol

4.  S

## Process

```         
-   R and Github
-   Discord
-   Co-working sessions/regular meetings
-   Organizing
    tasks/[issues](https://github.com/science-collective/scoping-review/issues)/[roadmap](https://github.com/science-collective/scoping-review/blob/main/ROADMAP.md)
-   Reflections
```

## Protocol

[Registration link](https://doi.org/10.17605/OSF.IO/K9DR5)

Search several databases...

But then came OpenAlex

Included all our databases and more.

## Search

See review-stages.qmd
